export const inputconfig = {
  email: {
    placeholder: "email",
    name: "email",
    type: "email",
    label: "Enter email",
    req: true,
  },
  password: {
    placeholder: "password",
    name: "password",
    type: "password",
    label: "Enter password",
    req: true,
  },

  firstName: {
    placeholder: "first name",
    name: "firstName",
    type: "text",
    label: "Enter First Name",
    req: true,
  },
  lastName: {
    placeholder: "last name",
    name: "lastName",
    type: "text",
    label: "Enter Last Name",
    req: true,
  },
  age: {
    placeholder: "age",
    name: "age",
    type: "number",
    label: "Enter Age",
    req: true,
  },
  target: {
    placeholder: "target",
    name: "target",
    type: "text",
    label: "Enter Target",
    req: true,
  },
  pressure: {
    placeholder: "pressure",
    name: "pressure",
    type: "number",
    label: "Enter Pressure",
    req: true,
  },
  index: {
    placeholder: "index",
    name: "index",
    type: "number",
    label: "Enter Index",
    req: true,
  },
  diagnosis: {
    placeholder: "diagnosis",
    name: "diagnosis",
    type: "text",
    label: "Enter Diagnosis",
    req: true,
  },
  lastVisit: {
    placeholder: "lastVisit",
    name: "lastVisit",
    type: "date",
    label: "Enter Last Visit",
    req: true,
  },
  search: {
    placeholder: "search",
    name: "search",
    type: "text",
    label: "Search",
    req: false,
  },
  dateVisit: {
    placeholder: "dateVisit",
    name: "dateVisit",
    type: "date",
    label: "Date of visit",
    req: true,
  },

  checkbox: {
    placeholder: "pastVisit",
    name: "pastVisit",
    type: "checkbox",
    label: "Past visit",
    req: false,
  },
};
